# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Chennam-Sravani56/a92d75718798d52805e49bf08809ab07/untitled0.ipynb
"""

#Women Safety Analysis in Indian Cities Using Tweets

# 1. Install necessary packages
!pip install pandas textblob matplotlib seaborn

# 2. Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
from IPython.display import display, HTML

# 3. Load your dataset
# Make sure your CSV has columns: 'tweet' and 'city'
# Example CSV: tweets.csv
# tweet,city
# "Feeling unsafe walking alone at night in Delhi.","Delhi"
# "Great police presence in Bangalore, feels safe!","Bangalore"

from google.colab import files
uploaded = files.upload()

# Assuming the uploaded file is 'tweets.csv'
df = pd.read_csv(list(uploaded.keys())[0])

# 4. Preprocess tweets (basic cleaning)
df['tweet'] = df['tweet'].str.lower()  # Convert to lowercase
df['tweet'] = df['tweet'].str.replace(r'[^\w\s]', '', regex=True)  # Remove punctuation

# 5. Sentiment Analysis using TextBlob
def get_sentiment(text):
    analysis = TextBlob(text)
    if analysis.sentiment.polarity > 0:
        return "Positive"
    elif analysis.sentiment.polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['tweet'].apply(get_sentiment)

# 6. Display sentiment count by city
sentiment_count = df.groupby(['city', 'sentiment']).size().unstack().fillna(0)
print(sentiment_count)

# 7. Visualization
plt.figure(figsize=(10,6))
sentiment_count.plot(kind='bar', stacked=True)
plt.title("Sentiment Analysis of Women Safety Tweets by City")
plt.ylabel("Number of Tweets")
plt.xlabel("City")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 8. Display some tweets with sentiments
display(df.head(10))

# 9. HTML link to Twitter (directs to Twitter web page)
display(HTML("""
<h3>Check Women's Safety Tweets on Twitter:</h3>
<a href="https://twitter.com/search?q=women%20safety%20india&src=typed_query" target="_blank">
Click here to go to Twitter
</a>
"""))
user_tweet = input("Enter your tweet about women safety: ").lower()
user_tweet_clean = ''.join(c for c in user_tweet if c.isalnum() or c.isspace())  # basic cleaning
user_sentiment = get_sentiment(user_tweet_clean)
print(f"The sentiment of your tweet is: {user_sentiment}")